### ISSUE TITLE
New integration for Status.io

### ISSUE THREAD

**Issue by pcolmer** [xmatters/xMatters-Labs#25]
I've created an outbound integration for xMatters that updates a Status.io dashboard when xMatters events are created or terminated for components on the dashboard.

https://github.com/linaro-its/xm-labs-statusio

**Comment by xMTinkerer** [comment]
Hey @pcolmer! This is awesome thanks for putting this together. 
Since this is primarily comprised of steps, I am putting it under the steps repository here: https://github.com/xmatters/xMatters-Labs-Flow-Steps/

I added a screen shot and a logo to the steps, which can better callout what product they are for. 

But great work putting this together! Thanks for your contribution.
